import { app } from 'electron'
import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http'
import { promises as fs } from 'node:fs'
import { randomBytes, timingSafeEqual } from 'node:crypto'
import { join } from 'node:path'
import { parseHookMessage, type AgentHookMessage } from './hook-event'

// A loopback listener that Claude Code's hooks report into.
//
// Deliberately separate from the mobile bridge: agent signals have to work with
// the bridge switched off, and this socket binds to 127.0.0.1 only — it is never
// exposed to the tailnet.
//
// The port is ephemeral and the token is regenerated per launch, so the relay
// script is rewritten on every start. A hook that fires against a stale port
// just gets connection-refused, which is instant on loopback and swallowed by
// the script.

const MAX_BODY_BYTES = 64 * 1024
/** Header the relay uses to name its terminal, so the body stays Claude's verbatim. */
const TERMINAL_HEADER = 'x-wterm-terminal'
const TOKEN_HEADER = 'x-wterm-token'

export type HookMessageHandler = (message: AgentHookMessage) => void

/**
 * The shell wTerm asks Claude to run on each hook.
 *
 * It must print absolutely nothing: a `UserPromptSubmit` hook's stdout is fed
 * back into the agent's prompt as context, so a stray curl progress line would
 * end up inside the user's conversation. It must also never fail: a non-zero
 * exit from a hook is surfaced to the user as an error, and wTerm being closed
 * is not an error worth interrupting an agent over.
 */
function relayScript(port: number, token: string): string {
  return `#!/bin/sh
# wTerm agent-signal relay. Regenerated by wTerm on every launch — edits are lost.
#
# Claude pipes the hook payload in on stdin; this forwards it verbatim to wTerm,
# naming the terminal from the environment wTerm exported into the PTY.
#
# Prints nothing (a UserPromptSubmit hook's stdout is injected into the prompt)
# and always exits 0 (a failed hook is shown to the user as an error).
curl -s -m 2 -o /dev/null \\
  -X POST 'http://127.0.0.1:${port}/hook' \\
  -H 'content-type: application/json' \\
  -H '${TOKEN_HEADER}: ${token}' \\
  -H "${TERMINAL_HEADER}: \${WTERM_TERMINAL_ID:-}" \\
  --data-binary @- >/dev/null 2>&1
exit 0
`
}

function tokensMatch(presented: string | undefined, expected: string): boolean {
  if (!presented) return false
  const a = Buffer.from(presented)
  const b = Buffer.from(expected)
  return a.length === b.length && timingSafeEqual(a, b)
}

export class AgentHookServer {
  private server: Server | null = null
  private token = ''
  private handler: HookMessageHandler | null = null

  /** Where the relay script lives. Stable across launches; contents are not. */
  relayPath(): string {
    return join(app.getPath('userData'), 'agent-hook.sh')
  }

  /** Called for every well-formed hook event. */
  onMessage(handler: HookMessageHandler): void {
    this.handler = handler
  }

  async start(): Promise<void> {
    if (this.server) return
    this.token = randomBytes(24).toString('base64url')

    const server = createServer((req, res) => {
      void this.handle(req, res)
    })
    await new Promise<void>((resolve, reject) => {
      server.once('error', reject)
      // Port 0 = let the OS pick; loopback only, never the tailnet.
      server.listen(0, '127.0.0.1', () => resolve())
    })
    this.server = server

    const address = server.address()
    const port = typeof address === 'object' && address !== null ? address.port : 0
    if (port === 0) throw new Error('agent hook server did not get a port')
    await this.writeRelay(port)
  }

  async stop(): Promise<void> {
    const server = this.server
    if (!server) return
    this.server = null
    await new Promise<void>((resolve) => server.close(() => resolve()))
  }

  private async writeRelay(port: number): Promise<void> {
    const path = this.relayPath()
    await fs.writeFile(path, relayScript(port, this.token), { mode: 0o700 })
    // writeFile only applies mode when it creates the file, so set it either way.
    await fs.chmod(path, 0o700)
  }

  private async handle(req: IncomingMessage, res: ServerResponse): Promise<void> {
    if (req.method !== 'POST' || (req.url ?? '').split('?')[0] !== '/hook') {
      res.writeHead(404).end()
      return
    }
    if (!tokensMatch(req.headers[TOKEN_HEADER] as string | undefined, this.token)) {
      res.writeHead(401).end()
      return
    }

    const body = await readBody(req)
    // Answer before doing anything with the payload: the agent is blocked on
    // this request finishing, so it should never wait on wTerm's own work.
    res.writeHead(204).end()

    const terminalId = (req.headers[TERMINAL_HEADER] as string | undefined) ?? null
    const message = parseHookMessage(body, terminalId)
    if (!message) return
    try {
      this.handler?.(message)
    } catch (err) {
      console.error('[agent-hook] handler failed', err)
    }
  }
}

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve) => {
    let data = ''
    req.on('data', (chunk) => {
      data += chunk
      if (data.length > MAX_BODY_BYTES) req.destroy()
    })
    req.on('end', () => resolve(data))
    req.on('error', () => resolve(''))
  })
}
